apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dmilan77/docker-sample-restapp-flask.git
    targetRevision: HEAD
    path: gitopsyaml
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
